const gen2 = [

    {
        "nameid": "chikorita",
        "generation": 1 ,
        "number": 152,
        "name": "Chikorita",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "bayleef",
        "generation": 1 ,
        "number": 153,
        "name": "Bayleef",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "meganium",
        "generation": 1 ,
        "number": 154,
        "name": "Meganium",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "cyndaquil",
        "generation": 1 ,
        "number": 155,
        "name": "Cyndaquil",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "quilava",
        "generation": 1 ,
        "number": 156,
        "name": "Quilava",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "typhlosion",
        "generation": 1 ,
        "number": 157,
        "name": "Typhlosion",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "totodile",
        "generation": 1 ,
        "number": 158,
        "name": "Totodile",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "croconaw",
        "generation": 1 ,
        "number": 159,
        "name": "Croconaw",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "feraligatr",
        "generation": 1 ,
        "number": 160,
        "name": "Feraligatr",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "sentret",
        "generation": 1 ,
        "number": 161,
        "name": "Sentret",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "furret",
        "generation": 1 ,
        "number": 162,
        "name": "Furret",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "hoothoot",
        "generation": 1 ,
        "number": 163,
        "name": "Hoothoot",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "noctowl",
        "generation": 1 ,
        "number": 164,
        "name": "Noctowl",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "ledyba",
        "generation": 1 ,
        "number": 165,
        "name": "Ledyba",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "ledian",
        "generation": 1 ,
        "number": 166,
        "name": "Ledian",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "spinarak",
        "generation": 1 ,
        "number": 167,
        "name": "Spinarak",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "ariados",
        "generation": 1 ,
        "number": 168,
        "name": "Ariados",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "crobat",
        "generation": 1 ,
        "number": 169,
        "name": "Crobat",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "chinchou",
        "generation": 1 ,
        "number": 170,
        "name": "Chinchou",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "lanturn",
        "generation": 1 ,
        "number": 171,
        "name": "Lanturn",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "pichu",
        "generation": 1 ,
        "number": 172,
        "name": "Pichu",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "cleffa",
        "generation": 1 ,
        "number": 173,
        "name": "Cleffa",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "igglybuff",
        "generation": 1 ,
        "number": 174,
        "name": "Igglybuff",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "togepi",
        "generation": 1 ,
        "number": 175,
        "name": "Togepi",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "togetic",
        "generation": 1 ,
        "number": 176,
        "name": "Togetic",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "natu",
        "generation": 1 ,
        "number": 177,
        "name": "Natu",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "xatu",
        "generation": 1 ,
        "number": 178,
        "name": "Xatu",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "mareep",
        "generation": 1 ,
        "number": 179,
        "name": "Mareep",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "flaaffy",
        "generation": 1 ,
        "number": 180,
        "name": "Flaaffy",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "ampharos",
        "generation": 1 ,
        "number": 181,
        "name": "Ampharos",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "bellossom",
        "generation": 1 ,
        "number": 182,
        "name": "Bellossom",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "marill",
        "generation": 1 ,
        "number": 183,
        "name": "Marill",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "azumarill",
        "generation": 1 ,
        "number": 184,
        "name": "Azumarill",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "sudowoodo",
        "generation": 1 ,
        "number": 185,
        "name": "Sudowoodo",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "politoed",
        "generation": 1 ,
        "number": 186,
        "name": "Politoed",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "hoppip",
        "generation": 1 ,
        "number": 187,
        "name": "Hoppip",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "skiploom",
        "generation": 1 ,
        "number": 188,
        "name": "Skiploom",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "jumpluff",
        "generation": 1 ,
        "number": 189,
        "name": "Jumpluff",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "aipom",
        "generation": 1 ,
        "number": 190,
        "name": "Aipom",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "sunkern",
        "generation": 1 ,
        "number": 191,
        "name": "Sunkern",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "sunflora",
        "generation": 1 ,
        "number": 192,
        "name": "Sunflora",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "yanma",
        "generation": 1 ,
        "number": 193,
        "name": "Yanma",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "wooper",
        "generation": 1 ,
        "number": 194,
        "name": "Wooper",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "quagsire",
        "generation": 1 ,
        "number": 195,
        "name": "Quagsire",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "espeon",
        "generation": 1 ,
        "number": 196,
        "name": "Espeon",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "umbreon",
        "generation": 1 ,
        "number": 197,
        "name": "Umbreon",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "murkrow",
        "generation": 1 ,
        "number": 198,
        "name": "Murkrow",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "slowking",
        "generation": 1 ,
        "number": 199,
        "name": "Slowking",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "misdreavus",
        "generation": 1 ,
        "number": 200,
        "name": "Misdreavus",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "unown",
        "generation": 1 ,
        "number": 201,
        "name": "Unown",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "wobbuffet",
        "generation": 1 ,
        "number": 202,
        "name": "Wobbuffet",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "girafarig",
        "generation": 1 ,
        "number": 203,
        "name": "Girafarig",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "pineco",
        "generation": 1 ,
        "number": 204,
        "name": "Pineco",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "forretress",
        "generation": 1 ,
        "number": 205,
        "name": "Forretress",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "dunsparce",
        "generation": 1 ,
        "number": 206,
        "name": "Dunsparce",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "gligar",
        "generation": 1 ,
        "number": 207,
        "name": "Gligar",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "steelix",
        "generation": 1 ,
        "number": 208,
        "name": "Steelix",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "snubbull",
        "generation": 1 ,
        "number": 209,
        "name": "Snubbull",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "granbull",
        "generation": 1 ,
        "number": 210,
        "name": "Granbull",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "qwilfish",
        "generation": 1 ,
        "number": 211,
        "name": "Qwilfish",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "scizor",
        "generation": 1 ,
        "number": 212,
        "name": "Scizor",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "shuckle",
        "generation": 1 ,
        "number": 213,
        "name": "Shuckle",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "heracross",
        "generation": 1 ,
        "number": 214,
        "name": "Heracross",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "sneasel",
        "generation": 1 ,
        "number": 215,
        "name": "Sneasel",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "teddiursa",
        "generation": 1 ,
        "number": 216,
        "name": "Teddiursa",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "ursaring",
        "generation": 1 ,
        "number": 217,
        "name": "Ursaring",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "slugma",
        "generation": 1 ,
        "number": 218,
        "name": "Slugma",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "magcargo",
        "generation": 1 ,
        "number": 219,
        "name": "Magcargo",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "swinub",
        "generation": 1 ,
        "number": 220,
        "name": "Swinub",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "piloswine",
        "generation": 1 ,
        "number": 221,
        "name": "Piloswine",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "corsola",
        "generation": 1 ,
        "number": 222,
        "name": "Corsola",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "remoraid",
        "generation": 1 ,
        "number": 223,
        "name": "Remoraid",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "octillery",
        "generation": 1 ,
        "number": 224,
        "name": "Octillery",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "delibird",
        "generation": 1 ,
        "number": 225,
        "name": "Delibird",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "mantine",
        "generation": 1 ,
        "number": 226,
        "name": "Mantine",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "skarmory",
        "generation": 1 ,
        "number": 227,
        "name": "Skarmory",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "houndour",
        "generation": 1 ,
        "number": 228,
        "name": "Houndour",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "houndoom",
        "generation": 1 ,
        "number": 229,
        "name": "Houndoom",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "kingdra",
        "generation": 1 ,
        "number": 230,
        "name": "Kingdra",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "phanpy",
        "generation": 1 ,
        "number": 231,
        "name": "Phanpy",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "donphan",
        "generation": 1 ,
        "number": 232,
        "name": "Donphan",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "porygon",
        "generation": 1 ,
        "number": 233,
        "name": "Porygon",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "stantler",
        "generation": 1 ,
        "number": 234,
        "name": "Stantler",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "smeargle",
        "generation": 1 ,
        "number": 235,
        "name": "Smeargle",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "tyrogue",
        "generation": 1 ,
        "number": 236,
        "name": "Tyrogue",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "hitmontop",
        "generation": 1 ,
        "number": 237,
        "name": "Hitmontop",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "smoochum",
        "generation": 1 ,
        "number": 238,
        "name": "Smoochum",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "elekid",
        "generation": 1 ,
        "number": 239,
        "name": "Elekid",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "magby",
        "generation": 1 ,
        "number": 240,
        "name": "Magby",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "miltank",
        "generation": 1 ,
        "number": 241,
        "name": "Miltank",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "blissey",
        "generation": 1 ,
        "number": 242,
        "name": "Blissey",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "raikou",
        "generation": 1 ,
        "number": 243,
        "name": "Raikou",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "entei",
        "generation": 1 ,
        "number": 244,
        "name": "Entei",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "suicune",
        "generation": 1 ,
        "number": 245,
        "name": "Suicune",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "larvitar",
        "generation": 1 ,
        "number": 246,
        "name": "Larvitar",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "pupitar",
        "generation": 1 ,
        "number": 247,
        "name": "Pupitar",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "tyranitar",
        "generation": 1 ,
        "number": 248,
        "name": "Tyranitar",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "lugia",
        "generation": 1 ,
        "number": 249,
        "name": "Lugia",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "ho-oh",
        "generation": 1 ,
        "number": 250,
        "name": "Ho-Oh",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "celebi",
        "generation": 1 ,
        "number": 251,
        "name": "Celebi",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },

]