const gen3 = [

    {
        "nameid": "treecko",
        "generation": 3 ,
        "number": 152,
        "name": "Treecko",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "grovyle",
        "generation": 3 ,
        "number": 153,
        "name": "Grovyle",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "sceptile",
        "generation": 3 ,
        "number": 154,
        "name": "Sceptile",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "torchic",
        "generation": 3 ,
        "number": 155,
        "name": "Torchic",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "combusken",
        "generation": 3 ,
        "number": 156,
        "name": "Combusken",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "blaziken",
        "generation": 3 ,
        "number": 157,
        "name": "Blaziken",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "mudkip",
        "generation": 3 ,
        "number": 158,
        "name": "Mudkip",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "marshtomp",
        "generation": 3 ,
        "number": 159,
        "name": "Marshtomp",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "swampert",
        "generation": 3 ,
        "number": 160,
        "name": "Swampert",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "poochyena",
        "generation": 3 ,
        "number": 161,
        "name": "Poochyena",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "mightyena",
        "generation": 3 ,
        "number": 162,
        "name": "Mightyena",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "zigzagoon",
        "generation": 3 ,
        "number": 163,
        "name": "Zigzagoon",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "linoone",
        "generation": 3 ,
        "number": 164,
        "name": "Linoone",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "wurmple",
        "generation": 3 ,
        "number": 165,
        "name": "Wurmple",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "silcoon",
        "generation": 3 ,
        "number": 166,
        "name": "Silcoon",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "beautifly",
        "generation": 3 ,
        "number": 167,
        "name": "Beautifly",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "cascoon",
        "generation": 3 ,
        "number": 168,
        "name": "Cascoon",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "dustox",
        "generation": 3 ,
        "number": 169,
        "name": "Dustox",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "lotad",
        "generation": 3 ,
        "number": 170,
        "name": "Lotad",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "lombre",
        "generation": 3 ,
        "number": 171,
        "name": "Lombre",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "ludicolo",
        "generation": 3 ,
        "number": 172,
        "name": "Ludicolo",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "seedot",
        "generation": 3 ,
        "number": 173,
        "name": "Seedot",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "nuzleaf",
        "generation": 3 ,
        "number": 174,
        "name": "Nuzleaf",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "shiftry",
        "generation": 3 ,
        "number": 175,
        "name": "Shiftry",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "taillow",
        "generation": 3 ,
        "number": 176,
        "name": "Taillow",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "swellow",
        "generation": 3 ,
        "number": 177,
        "name": "Swellow",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "wingull",
        "generation": 3 ,
        "number": 178,
        "name": "Wingull",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "pelipper",
        "generation": 3 ,
        "number": 179,
        "name": "Pelipper",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "ralts",
        "generation": 3 ,
        "number": 180,
        "name": "Ralts",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "kirlia",
        "generation": 3 ,
        "number": 181,
        "name": "Kirlia",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "gardevoir",
        "generation": 3 ,
        "number": 182,
        "name": "Gardevoir",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "surskit",
        "generation": 3 ,
        "number": 183,
        "name": "Surskit",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "masquerain",
        "generation": 3 ,
        "number": 184,
        "name": "Masquerain",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "shroomish",
        "generation": 3 ,
        "number": 185,
        "name": "Shroomish",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "breloom",
        "generation": 3 ,
        "number": 186,
        "name": "Breloom",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "slakoth",
        "generation": 3 ,
        "number": 187,
        "name": "Slakoth",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "vigoroth",
        "generation": 3 ,
        "number": 188,
        "name": "Vigoroth",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "slaking",
        "generation": 3 ,
        "number": 189,
        "name": "Slaking",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "nincada",
        "generation": 3 ,
        "number": 190,
        "name": "Nincada",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "ninjask",
        "generation": 3 ,
        "number": 191,
        "name": "Ninjask",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "shedinja",
        "generation": 3 ,
        "number": 192,
        "name": "Shedinja",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "whismur",
        "generation": 3 ,
        "number": 193,
        "name": "Whismur",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "loudred",
        "generation": 3 ,
        "number": 194,
        "name": "Loudred",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "exploud",
        "generation": 3 ,
        "number": 195,
        "name": "Exploud",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "makuhita",
        "generation": 3 ,
        "number": 196,
        "name": "Makuhita",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "hariyama",
        "generation": 3 ,
        "number": 197,
        "name": "Hariyama",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "azurill",
        "generation": 3 ,
        "number": 198,
        "name": "Azurill",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "nosepass",
        "generation": 3 ,
        "number": 199,
        "name": "Nosepass",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "skitty",
        "generation": 3 ,
        "number": 200,
        "name": "Skitty",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "delcatty",
        "generation": 3 ,
        "number": 201,
        "name": "Delcatty",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "sableye",
        "generation": 3 ,
        "number": 202,
        "name": "Sableye",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "mawile",
        "generation": 3 ,
        "number": 203,
        "name": "Mawile",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "aron",
        "generation": 3 ,
        "number": 204,
        "name": "Aron",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "lairon",
        "generation": 3 ,
        "number": 205,
        "name": "Lairon",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "aggron",
        "generation": 3 ,
        "number": 206,
        "name": "Aggron",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "meditite",
        "generation": 3 ,
        "number": 207,
        "name": "Meditite",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "medicham",
        "generation": 3 ,
        "number": 208,
        "name": "Medicham",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "electrike",
        "generation": 3 ,
        "number": 209,
        "name": "Electrike",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "manectric",
        "generation": 3 ,
        "number": 210,
        "name": "Manectric",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "plusle",
        "generation": 3 ,
        "number": 211,
        "name": "Plusle",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "minun",
        "generation": 3 ,
        "number": 212,
        "name": "Minun",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "volbeat",
        "generation": 3 ,
        "number": 213,
        "name": "Volbeat",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "illumise",
        "generation": 3 ,
        "number": 214,
        "name": "Illumise",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "roselia",
        "generation": 3 ,
        "number": 215,
        "name": "Roselia",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "gulpin",
        "generation": 3 ,
        "number": 216,
        "name": "Gulpin",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "swalot",
        "generation": 3 ,
        "number": 217,
        "name": "Swalot",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "carvanha",
        "generation": 3 ,
        "number": 218,
        "name": "Carvanha",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "sharpedo",
        "generation": 3 ,
        "number": 219,
        "name": "Sharpedo",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "wailmer",
        "generation": 3 ,
        "number": 220,
        "name": "Wailmer",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "wailord",
        "generation": 3 ,
        "number": 221,
        "name": "Wailord",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "numel",
        "generation": 3 ,
        "number": 222,
        "name": "Numel",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "camerupt",
        "generation": 3 ,
        "number": 223,
        "name": "Camerupt",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "torkoal",
        "generation": 3 ,
        "number": 224,
        "name": "Torkoal",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "spoink",
        "generation": 3 ,
        "number": 225,
        "name": "Spoink",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "grumpig",
        "generation": 3 ,
        "number": 226,
        "name": "Grumpig",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "spinda",
        "generation": 3 ,
        "number": 227,
        "name": "Spinda",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "trapinch",
        "generation": 3 ,
        "number": 228,
        "name": "Trapinch",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "vibrava",
        "generation": 3 ,
        "number": 229,
        "name": "Vibrava",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "flygon",
        "generation": 3 ,
        "number": 230,
        "name": "Flygon",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "cacnea",
        "generation": 3 ,
        "number": 231,
        "name": "Cacnea",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "cacturne",
        "generation": 3 ,
        "number": 232,
        "name": "Cacturne",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "swablu",
        "generation": 3 ,
        "number": 233,
        "name": "Swablu",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "altaria",
        "generation": 3 ,
        "number": 234,
        "name": "Altaria",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "zangoose",
        "generation": 3 ,
        "number": 235,
        "name": "Zangoose",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "seviper",
        "generation": 3 ,
        "number": 236,
        "name": "Seviper",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "lunatone",
        "generation": 3 ,
        "number": 237,
        "name": "Lunatone",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "solrock",
        "generation": 3 ,
        "number": 238,
        "name": "Solrock",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "barboach",
        "generation": 3 ,
        "number": 239,
        "name": "Barboach",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "whiscash",
        "generation": 3 ,
        "number": 240,
        "name": "Whiscash",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "corphish",
        "generation": 3 ,
        "number": 241,
        "name": "Corphish",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "crawdaunt",
        "generation": 3 ,
        "number": 242,
        "name": "Crawdaunt",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "baltoy",
        "generation": 3 ,
        "number": 243,
        "name": "Baltoy",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "claydol",
        "generation": 3 ,
        "number": 244,
        "name": "Claydol",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "lileep",
        "generation": 3 ,
        "number": 245,
        "name": "Lileep",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "cradily",
        "generation": 3 ,
        "number": 246,
        "name": "Cradily",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "anorith",
        "generation": 3 ,
        "number": 247,
        "name": "Anorith",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "armaldo",
        "generation": 3 ,
        "number": 248,
        "name": "Armaldo",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "feebas",
        "generation": 3 ,
        "number": 249,
        "name": "Feebas",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "milotic",
        "generation": 3 ,
        "number": 250,
        "name": "Milotic",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "castform",
        "generation": 3 ,
        "number": 251,
        "name": "Castform",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "kecleon",
        "generation": 3 ,
        "number": 252,
        "name": "Kecleon",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "shuppet",
        "generation": 3 ,
        "number": 253,
        "name": "Shuppet",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "banette",
        "generation": 3 ,
        "number": 254,
        "name": "Banette",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "duskull",
        "generation": 3 ,
        "number": 255,
        "name": "Duskull",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "dusclops",
        "generation": 3 ,
        "number": 256,
        "name": "Dusclops",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "tropius",
        "generation": 3 ,
        "number": 257,
        "name": "Tropius",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "chimecho",
        "generation": 3 ,
        "number": 258,
        "name": "Chimecho",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "absol",
        "generation": 3 ,
        "number": 259,
        "name": "Absol",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "wynaut",
        "generation": 3 ,
        "number": 260,
        "name": "Wynaut",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "snorunt",
        "generation": 3 ,
        "number": 261,
        "name": "Snorunt",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "glalie",
        "generation": 3 ,
        "number": 262,
        "name": "Glalie",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "spheal",
        "generation": 3 ,
        "number": 263,
        "name": "Spheal",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "sealeo",
        "generation": 3 ,
        "number": 264,
        "name": "Sealeo",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "walrein",
        "generation": 3 ,
        "number": 265,
        "name": "Walrein",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "clamperl",
        "generation": 3 ,
        "number": 266,
        "name": "Clamperl",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "huntail",
        "generation": 3 ,
        "number": 267,
        "name": "Huntail",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "gorebyss",
        "generation": 3 ,
        "number": 268,
        "name": "Gorebyss",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "relicanth",
        "generation": 3 ,
        "number": 269,
        "name": "Relicanth",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "luvdisc",
        "generation": 3 ,
        "number": 270,
        "name": "Luvdisc",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "bagon",
        "generation": 3 ,
        "number": 271,
        "name": "Bagon",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "shelgon",
        "generation": 3 ,
        "number": 272,
        "name": "Shelgon",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "salamence",
        "generation": 3 ,
        "number": 273,
        "name": "Salamence",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "beldum",
        "generation": 3 ,
        "number": 274,
        "name": "Beldum",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "metang",
        "generation": 3 ,
        "number": 275,
        "name": "Metang",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "metagross",
        "generation": 3 ,
        "number": 276,
        "name": "Metagross",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "regirock",
        "generation": 3 ,
        "number": 277,
        "name": "Regirock",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "regice",
        "generation": 3 ,
        "number": 278,
        "name": "Regice",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "registeel",
        "generation": 3 ,
        "number": 279,
        "name": "Registeel",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "latias",
        "generation": 3 ,
        "number": 280,
        "name": "Latias",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "latios",
        "generation": 3 ,
        "number": 281,
        "name": "Latios",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "kyogre",
        "generation": 3 ,
        "number": 282,
        "name": "Kyogre",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "groudon",
        "generation": 3 ,
        "number": 283,
        "name": "Groudon",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "rayquaza",
        "generation": 3 ,
        "number": 284,
        "name": "Rayquaza",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "jirachi",
        "generation": 3 ,
        "number": 285,
        "name": "Jirachi",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },
        {
        "nameid": "deoxys",
        "generation": 3 ,
        "number": 286,
        "name": "Deoxys",
        "species": "",
        "type": [""],
        "ability": [""],
        "height": "",
        "weight": "",
        "description": ""
        },

]